
export enum GameState {
    IDLE = 'IDLE',
    REMOVING_TILES = 'REMOVING_TILES',
    APPLYING_GRAVITY = 'APPLYING_GRAVITY',
    SPAWNING_TILES = 'SPAWNING_TILES',
    SHUFFLING = 'SHUFFLING',
    LOSE = 'GAME_OVER',
    WIN = 'WIN'
}